### ISSUE TITLE
Default sorting and some form of auto refresh/bundling with a webserver?

### ISSUE THREAD

**Issue by naitmare01** [EvotecIT/Dashimo#1]
Hi,

First I want to say that this is a great module and it has potential! 

I have two question or feedback on the module. 

1. Any chance you plan to add default sorting on the data tables?
2. Do you plan to bundle the module with some sort of webserver(e.g. nginx) or is this a strictly ad-hoc html-report-builder?

**Comment by PrzemyslawKlys** [comment]
What would be your choice on Default sorting? Like, define a column over which to sort? Or how do you imagine the implementation?

I wasn't planning for that. There are many options IIS/Ngix/Apache or strictly PowerShell based like https://github.com/PowerShell/Polaris or https://github.com/Badgerati/Pode

**Comment by naitmare01** [comment]
I was thinking the sorting could be implemented something along the lines of defining a column name or index to sort. 

That would make sense if some would build a dynamic dashboard that must auto-update every x seconds and always display the data in a controlled order. 

`Table -HideFooter -DataTable $DataSetForest.ForestDomainControllers -DefaultSortColumn Site`
`Table -HideFooter -DataTable $DataSetForest.ForestDomainControllers -DefaultSortColumnIndex 2`

I see, and since it is a static html-file it isnt that hard to make a schedule task and drop the file in the iis-root folder or the same with cron and nginx.

**Comment by PrzemyslawKlys** [comment]
Btw. Autorefresh is already there. Dashboard takes -AutoRefresh parameter in seconds. 0 means no refresh. 
Sorting will be added. Thanks for this feature request.

**Comment by PrzemyslawKlys** [comment]
This has been now added. The release is pending, deciding whether to wait for a bit more features or release. I've also added conditional formatting.

**Comment by PrzemyslawKlys** [comment]
This is now live.
