### ISSUE TITLE
Feature Request: Hyperlinks in Cells

### ISSUE THREAD

**Issue by ferwe** [EvotecIT/Dashimo#11]
Maybe it would be a nice feature to have a automatic link grabber.
Something like. if cell starts wirh "http:" create a hyperlink.
If a cell start with "\\" create a file-link.
Hyperlinks for URLs and Files.

I'm not sure if this is an easy thing to do, but i also think it is possible. 
What do you think?

**Comment by PrzemyslawKlys** [comment]
you can add hyperlinks already. You just need to use -InvokeHTML switch

**Comment by ferwe** [comment]
Man, you are too fast in answering 👍

**Comment by PrzemyslawKlys** [comment]
I just happen to have GitHub open a lot, and my mobile sends me notifications as well.
