### ISSUE TITLE
Page always prompts to translate from french. 

### ISSUE THREAD

**Issue by ChrisWalker80** [EvotecIT/Dashimo#12]
Every time chrome loads these tables it detects it as french and asks to translate it. For reference, I'm in the US.

**Comment by PrzemyslawKlys** [comment]
That's highly unlikely. Is the content in French? Have you tried different browsers? Private windows and so on? I'm using Chrome myself and I haven't seen any issue like that.

**Comment by ChrisWalker80** [comment]
So after a few updates to my script it stopped doing it. I'm not really sure what was going on, but I'm no longer confident it was this module, ha. 

P.S. I really like the module, will probably be working with it more in the coming weeks and may put in some feature requests as I work through it.

**Comment by PrzemyslawKlys** [comment]
I'm glad you like it. I like it too. I'm very proud of it ;-) It will be developed further with more and more features as I need them. Feel free to open Feature Requests.
