### ISSUE TITLE
Question about the DefaultSortIndex option

### ISSUE THREAD

**Issue by harleykin** [EvotecIT/Dashimo#16]
This is working great, except that I would really like for it to be sorted in the opposite direction.  Is there a way to specify assorting by descending instead by default?  :)

**Comment by PrzemyslawKlys** [comment]
Should be easy to add if its not there. I will take a look sometime this week. I’m currently on psconf.eu so a bit out of touch.

**Comment by harleykin** [comment]
Oooh nice!  I'm jealous.  Have fun!  :)

**Comment by PrzemyslawKlys** [comment]
It's already built-in:

```powershell
        [string[]] $DefaultSortColumn,
        [int[]] $DefaultSortIndex,
        [ValidateSet('Ascending', 'Descending')][string] $DefaultSortOrder = 'Ascending'
```

So just use it :) It should work

**Comment by harleykin** [comment]
Ah, that's what I was looking for.  Cheers!  :D
