### ISSUE TITLE
After 0.0.11 update -DefaultSortColumn seems to be broken

### ISSUE THREAD

**Issue by maotar** [EvotecIT/Dashimo#17]
Tested on two different computers and with multiple reports, column is no longer sorted as specified.

**Comment by PrzemyslawKlys** [comment]
I'll take a look. Sorry about that.

**Comment by PrzemyslawKlys** [comment]
Fixed

**Comment by maotar** [comment]
Confirmed resolved, thanks a lot for the quick fix!
