### ISSUE TITLE
Colours do not show when run Powershell 6

### ISSUE THREAD

**Issue by mckayit** [EvotecIT/Dashimo#19]
When i use the followinf gode in Powershell 5.x it works but when it is run in Powershell 6   there is no colours.

the Cells are white even though they should be Darkorange.

Any help to get this working in POS6 would be great.

                Dashboard -Name "Office365 Status" -FilePath $outputfile -AutoRefresh 300 {
                    Tab -Name 'Current Issues' {
                        Section -Invisible {
                            Section -Name 'Current Issues' {
                                Table -DataTable $p1  -Style cell-border {

                                    TableConditionalFormatting -Name 'Severity' -ComparisonType string -Operator eq -Value "Sev1" -Color White -BackgroundColor Crimson -Row
                                    TableConditionalFormatting -Name 'Severity' -ComparisonType string -Operator eq -Value "Sev2" -Color White -BackgroundColor DarkOrange -Row
                                    TableConditionalFormatting -Name 'Severity' -ComparisonType string -Operator eq -Value "Sev3" -Color White -BackgroundColor Yellow -Row

                                }
                            }
            
                        }
                    }

**Comment by PrzemyslawKlys** [comment]
```
Update-Module Dashimo
```

Should work now. It seems that PS 6 and PS5.1 output JSON with one less space so had to take that into account. Not sure if there's a better way yet. Maybe I'll rebuild this in future.

**Comment by mckayit** [comment]
Works a Dream now.
Amazing quick Turn around.
