### ISSUE TITLE
Titles for Tables within Panels

### ISSUE THREAD

**Issue by svbuckle** [EvotecIT/Dashimo#20]
Hello,
 I am just wondering if there is an option to add titles to the Tables within a Panel?  I have two sets of data from different sources, which should be the same.  To make it easier to identify which is which I have been asked to add a title for each panel.

Is this possible?

I have tried to put the "Name" switch into the table but it is not showing.

Kind Regards
Sean Buckle

**Comment by PrzemyslawKlys** [comment]
Take a look here: 

- https://evotec.xyz/all-your-html-tables-are-belong-to-us/

Basically, you need to use TableHeader with just the Title parameter. It says in the article you need to use AddRow switch as well but actually, you don't anymore. 

```
$Properties = @(
    'Name'
    'Id'
    'PriorityClass'
    'FileVersion'
    'HandleCount'
    'WorkingSet'
    'PagedMemorySize'
    'PrivateMemorySize'
    'VirtualMemorySize'
    'TotalProcessorTime'
    'SI'
    'Handles'
    'VM'
    'WS'
    'PM'
    'NPM',
    'PATH'
)
$ProcessesAll = Get-Process | Select-Object -First 30 -Property $Properties
Dashboard -Name 'My title' -FilePath $PSScriptRoot\Example03.html -Show {
    Section -Name 'Show basic way to merge column names, giving title on top of it' {
        Panel {
            Table -DataTable $ProcessesAll -HideFooter -DisableResponsiveTable {
                TableHeader -Names 'Name', 'ID' -Title 'Process Information' -BackGroundColor Green
                TableHeader -Names 'PagedMemorySize', 'PrivateMemorySize', 'VirtualMemorySize' -Title 'Memory' -Color White -BackGroundColor Gainsboro
                TableHeader -Names 'Name', 'ID' -Color Red
                TableHeader -Title 'Process List - Example' -AddRow -Color Black
            }
        }
    }

```

**Comment by svbuckle** [comment]
Hi there,

Thank you that solved my issue, only had to update the PS module as well.

Once again thank you
Sean
