### ISSUE TITLE
Dynamic Tabs ForEach Loop Data

### ISSUE THREAD

**Issue by arag0nes** [EvotecIT/Dashimo#22]
Hey;

Would there be anyway to build tabs dynamically from data that's in a foreach loop?

im working to create a report from multiple vCenters and while I have the code working to generate a single report from each in the loop and email it, I was trying to figure out if I could just increment some Vars into a final report that has all the vCenter data in a tab for each.

I know that I can do

Tab -Name vCenter#1
Tab -Name vCenter#2
Tab -Name vCenter#3

but it would be awesome if this was dynamic that way if I add another vCenter to the mix I wouldn't have to add a Tab4  code

Another though would be if there was a way to append the data from the loop into a final Dashboard build?

thanks!

**Comment by PrzemyslawKlys** [comment]
Well, just because the syntax is a bit different doesn't mean you can't use foreach inside Dashboard.

```PowerShell
Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\Output\DashboardTabsLoop.html -Show {
    $Tabs = 'vCenter', 'vCenter1', 'vCenter2'
    foreach ($_ in $Tabs) {
        Tab -Name $_ {
            Section -Name 'Test' {
                $Process = Get-Process | Select-Object -First 5
                Table -DataTable $Process {
                    TableConditionalFormatting -Name 'ID' -ComparisonType number -Operator gt -Value 16000 -Color BlueViolet -Row
                    TableConditionalFormatting -Name 'PriorityClass' -ComparisonType string -Operator eq -Value 'Normal' -BackgroundColor Gold
                    TableConditionalFormatting -Name 'PriorityClass' -ComparisonType string -Operator eq -Value 'Idle' -BackgroundColor Gold -Color Green
                }
            }
        }
    }
    for ($i = 0; $i -lt 5; $i++) {
        Tab -Name "vCenter#$i" {
            Section -Name "Section Name$i" {
                $Process = Get-Process | Select-Object -First 5
                Table -DataTable $Process {
                    TableConditionalFormatting -Name 'ID' -ComparisonType number -Operator gt -Value 16000 -Color BlueViolet -Row
                    TableConditionalFormatting -Name 'PriorityClass' -ComparisonType string -Operator eq -Value 'Normal' -BackgroundColor Gold
                    TableConditionalFormatting -Name 'PriorityClass' -ComparisonType string -Operator eq -Value 'Idle' -BackgroundColor Gold -Color Green
                }
            }
        }
    }
}
```
You can use any specific feature of PowerShell inside Dashboard to create things in loops/switches/ifs and so on.
