### ISSUE TITLE
Embed HTML Link in table cell

### ISSUE THREAD

**Issue by hitze7** [EvotecIT/Dashimo#23]
Is there a way to embed an HTLM Link in a cell?  I have a PowerShell Script that gathers printer information from multiple sources and uses Dashimo to color code and present the information to our HelpDesk staff.  (btw, Dashimo cut my script by 1000+ lines of code that was previously manually creating the HTML page!!).  Each of the printers has an internal management page which is accessed via the devices IP address.  In the manual code, I was able to add a link to the printer in the HTLM output based on the device's IP address.  I would like to duplicate that ability in the Dashimo generated page.
Thanks,
Eric

**Comment by PrzemyslawKlys** [comment]
You need to follow the same pattern as shown in here: https://github.com/EvotecIT/PSWriteHTML/issues/30

Of course in your case, it will Be Dashboard/Tab/Section/Table. Since PSWriteHTML is Dashimo and vice versa the idea is the same. Let me know if that solves your issue.

**Comment by hitze7** [comment]
I already had the link built but I was missing the -invokeHTMLTags.  Thanks for you help with this.

**Comment by hitze7** [comment]
![PrinterStatus](https://user-images.githubusercontent.com/54112226/63043194-b8ba4680-be99-11e9-97b1-9713adef4da0.jpg)

**Comment by PrzemyslawKlys** [comment]
That looks awesome! Great idea!
