### ISSUE TITLE
Missing space character when using '-Collapsable'

### ISSUE THREAD

**Issue by whoot** [EvotecIT/Dashimo#24]
When using '-Collapsable' then the '(hide)' button is directly appended after the section text. Please insert a space character.

Example:
ThisismySectionText(hide)

**Comment by PrzemyslawKlys** [comment]
Thank you for reporting. I've fixed it in PSWriteHTML. After I publish new release it will be available in Dashimo. Please let me know if this is something urgent or it can wait couple of days?

**Comment by whoot** [comment]
Thanks for this fast response!
This is definetly something that can wait. 
I made a workaround by adding a space character at the end of the section name.
