### ISSUE TITLE
Code no longer working

### ISSUE THREAD

**Issue by Taomyn** [EvotecIT/Dashimo#6]
Hello,

I just saw your article at https://evotec.xyz/the-only-powershell-command-you-will-ever-need-to-find-out-who-did-what-in-active-directory and no matter what I change I keep finding code that doesn't work. I'm on a fresh system (Server 2016),  so importing the modules shouldn't be clashing with anything, yet when I ran the example code at the end of the article I get errors such as:

```
New-HTMLContent : A parameter cannot be found that matches parameter name 'Collapsed'.
At C:\Program Files\WindowsPowerShell\Modules\Dashimo\0.0.6\Dashimo.psm1:26 char:87
+ ... e -CanCollapse:$Collapsable -Invisible:$Invisible -Collapsed:$Collaps ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-HTMLContent], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-HTMLContent

```

When I remove that parameter, it doesn't get much further:

```
New-HTMLTable : A parameter cannot be found that matches parameter name 'Filtering'.
At C:\Program Files\WindowsPowerShell\Modules\Dashimo\0.0.6\Dashimo.psm1:66 char:763
+ ... aultSortOrder -Find $Find -OrderMulti:$OrderMulti -Filtering:$Filteri ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-HTMLTable], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-HTMLTable

```
I cannot find the two parameters mentioned in the latest version of PSWinReportingV2 so can you let me know what I'm missing? Thanks.

**Comment by PrzemyslawKlys** [comment]
Make sure to update dashimo and pswritehtml.

Install-module dashimo -force

**Comment by Taomyn** [comment]
Thanks, that seems to have sorted but I'm sure I did them both that way the first time as it's in the comments at the start of your code, plus I did close then re-open the powershell session to be sure to pick them up.

Anyway, now I need to figure this one out which I'm sure is an issue my side:

```
[Error] Server DC1.mydomain.lan: The RPC server is unavailable
[Error] Server DC1.mydomain.lan: The RPC server is unavailable
[Error] Server DC2.mydomain.lan: The RPC server is unavailable
[Error] Server DC1.mydomain.lan: The RPC server is unavailable
[Error] Server DC2.mydomain.lan: The RPC server is unavailable
[Error] Server DC2.mydomain.lan: The RPC server is unavailable
[Error] Server DC1.mydomain.lan: The RPC server is unavailable
[Error] Server DC2.mydomain.lan: The RPC server is unavailable

```

**Comment by PrzemyslawKlys** [comment]
That means usually problem with firewall, or lack of access to dcs from that server.
