### ISSUE TITLE
Possible to suppress auto-open in browser?

### ISSUE THREAD

**Issue by harleykin** [EvotecIT/Dashimo#7]
Is it possible to keep the results from automatically opening in the browser?  I'm thinking of amending a script I run via task scheduler to include a dashimo file, and I don't need a browser/tab opened for every time the script runs.

**Comment by PrzemyslawKlys** [comment]
Just remove the -Show? parameter?

**Comment by harleykin** [comment]
Mmmkay, I feel like an idiot.  That did it.  Thank you!  👍
