### ISSUE TITLE
Several Additions

### ISSUE THREAD

**Issue by g-pearl** [EvotecIT/Dashimo#8]
Would it be possible to add the following:

1.  Ability to Change the alignment of the Section Test
      A.  Like a parameter -alignment [Left, Right, Center]
2.  Ability to change the background color of the section
     A.   Like a parameter -BackGroundColor [Color]
3.  Ability to add precontent/postcontent when using a table in the section.
     A.   Like a Parameter -PreContent "Insert Pre Text Here"
     B.   Like a parameter -PostContent "Insert Post Text Here"
     C.   Would also be great to have the ability to insert a line break if multiple tables are used so they show up as stacked not side by side.
          i. maybe and option on both precontent/postcontent like -linebreak.

Thanks again I foresee this module becoming a vital tool in communicating with Non-Technical people.

Please let me know if you would like me to break this out into separate request for easier tracking

**Comment by PrzemyslawKlys** [comment]
Would this be good enough? 

```
Table -DataTable ... {

} -PreContent {

} -PostContent {

}
```

**Comment by g-pearl** [comment]
I think that would be great for the table additions.

**Comment by PrzemyslawKlys** [comment]
```PowerShell
Update-Module Dashimo
```

Here's a sample. Covers all your needs.

```PowerShell
$Process = Get-Process | Select-Object -First 1

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy03.html -Show {
    Section -Name 'Test1' -TextAlignment left -TextBackGroundColor BlueViolet {
        Table -DataTable $Process
        Table -DataTable $Process -PreContent {
            New-HTMLText -Text 'TestPreContent' -Color Coral -Alignment center
        } -PostContent {
            # Notice how I'm adding table below another table in a very specific scenario
            New-HTMLText -Text 'TestPostContent' -Color Coral -Alignment center
            Table -DataTable $Process
        }
    }
    Section -Name 'Test3' -BackgroundColor DarkOrange {
        Table -DataTable $Process
        Container {
            # a different way to add post and pre content
            Table -DataTable $Process1
            New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center
            Table -DataTable $Process
        }
    }
    Section -Name 'Test2' -Collapsable {
        Panel {
            Table -DataTable $Process
        }
        Panel {
            Table -DataTable $Process
        }
    }
}
```

**Comment by g-pearl** [comment]
Yes That looks like it does work.  Will I need to pull a new version of Dashimo?

**Comment by PrzemyslawKlys** [comment]
Yes. Simply `Update-Module Dashimo` which will download new versions of PSWriteHTML and any other required pre-requisites. That's why I said modifications aren't easy to overcome.

**Comment by g-pearl** [comment]
Looks like this may break -disablepaging & -disablesearchon the table section as well as the tableconditionalformatting.

**Comment by PrzemyslawKlys** [comment]
Did you test it and it broke it?

**Comment by g-pearl** [comment]
Yes I tried:
Table -DataTable $processes -Buttons @() -DisableSearch -HideFooter -DisablePaging and the whole table does not show up.

If I try the conditionalformating
and then this shows up above the table.

This is what I am currently have:

$Process = Get-Process | Select-Object -First 10

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy03.html -Show {
    Section -Name 'Test1' -TextAlignment left -TextBackGroundColor BlueViolet  {
        Table -DataTable $Process -PreContent {
            New-HTMLText -Text 'TestPreContent' -Color Black -Alignment Left
            TableConditionalFormatting -Name 'Name' -ComparisonType string -Operator eq -Value beremote -Color BlueViolet -BackgroundColor Red -Row
        }
    }
}

**Comment by PrzemyslawKlys** [comment]
Ye, lemme quickly fix it. I see where I did a mistake.

**Comment by PrzemyslawKlys** [comment]
``` PowerShell
Update-Module Dashimo
```

And let me know. 

```
$Process = Get-Process | Select-Object -First 30

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy03.html -Show {
    Section -Name 'Test1' -TextAlignment left -TextBackGroundColor BlueViolet {
        Table -DataTable $Process
        Table -DataTable $Process {
            TableConditionalFormatting -Name 'ID' -ComparisonType number -Operator gt -Value 16000 -Color BlueViolet -Row
            TableConditionalFormatting -Name 'PriorityClass' -ComparisonType string -Operator eq -Value 'Normal' -BackgroundColor Gold
            TableConditionalFormatting -Name 'PriorityClass' -ComparisonType string -Operator eq -Value 'Idle' -BackgroundColor Gold -Color Green
        } -PreContent {
            New-HTMLText -Text 'TestPreContent' -Color Coral -Alignment center
        } -PostContent {
            # Notice how I'm adding table below another table in a very specific scenario
            New-HTMLText -Text 'TestPostContent' -Color Coral -Alignment center
            Table -DataTable $Process
        }
    }
    Section -Name 'Test3' -BackgroundColor DarkOrange {
        Table -DataTable $Process -DisablePaging
        Container {
            # a different way to add post and pre content
            Table -DataTable $Process1
            New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center
            Table -DataTable $Process
        }
    }
    Section -Name 'Test2' -Collapsable {
        Panel {
            Table -DataTable $Process
        }
        Panel {
            Table -DataTable $Process
        }
    }
}
```
Seems to work

**Comment by PrzemyslawKlys** [comment]
Just so you know, PreContent or PostContent doesn't take TableConditionalFormatting. It's a separate ScriptBlock. Therefore either open it up as first as on example above or use -HTML { ... } as a way to provide input for TableConditionalFormatting. I may fix this in future but precontent and postcontent is for non-related data.

**Comment by PrzemyslawKlys** [comment]
Dashimo has to have version 0.0.8. I've now unlisted 0.0.7.

**Comment by g-pearl** [comment]
Thanks I think that gets it.  One last question and I will stop Promise!

If I have two table in the same section how can I force a line break between them so they are stacked not side by side?

Thanks for all your help today.

**Comment by PrzemyslawKlys** [comment]
Not sure I get it? Use Panel or Container? or Section within section?

**Comment by g-pearl** [comment]
This is what I have:

$Process = Get-Process | Select-Object -First 15 | Select name,Priorityclass,fileversion,handles,cpu

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy03.html -Show {
    Section -Name 'Test2' -Collapsable {
        Panel {
            Table -DataTable $Process -PreContent -{ New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center}
        }
        Panel {
            Table -DataTable $Process -PreContent { New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center}
        }
    }

}


How Can I get the tables like:
X
X

instead of
X  X

**Comment by PrzemyslawKlys** [comment]
3 different ways

```powershell
$Process = Get-Process | Select-Object -First 15 | Select name, Priorityclass, fileversion, handles, cpu

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy03.html -Show {
    Section -Name 'Test2' -Collapsable {
        Container {
            Panel {
                Table -DataTable $Process -PreContent { New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center}
            }
            Panel {
                Table -DataTable $Process -PreContent { New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center}
            }
        }
    }

}


$Process = Get-Process | Select-Object -First 15 | Select name, Priorityclass, fileversion, handles, cpu

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy04.html -Show {
    Panel {
        Section {
            Table -DataTable $Process -PreContent { New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center}
        }
        Section {
            Table -DataTable $Process -PreContent { New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center}
        }
    }

}

$Process = Get-Process | Select-Object -First 15 | Select name, Priorityclass, fileversion, handles, cpu

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy05.html -Show {

    Section -Name 'Test 4' {
        Table -DataTable $Process -PreContent {
            New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center
        } -PostContent {
            Table -DataTable $Process -PreContent {
                New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center
            }
        }
    }
}
```

**Comment by g-pearl** [comment]
OK I see now.  Sorry was slow on the uptake.

This is working as I expect:
$Process = Get-Process | Select-Object -First 15 | Select name,Priorityclass,fileversion,handles,cpu


Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy03.html -Show {
    Section -Name 'Test2' -Collapsable -Collapsed -TextAlignment left -TextColor Black -TextBackGroundColor Yellow {
        Table -DataTable $Process -buttons @() -DisableSearch -HideFooter -DisablePaging -PreContent{
            New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment left
        } -PostContent {        
            Table -DataTable $Process -buttons @() -DisableSearch -HideFooter -DisablePaging -PreContent{ New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment Left
        }
        }
    }

}


Is there a parameter to put table on left justification since I have removed the buttons/search/footer/paging?

**Comment by PrzemyslawKlys** [comment]
```
Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy03.html -Show {
    Section -Name 'Test2' -Collapsable {
        Container {
            Panel {
                Table -DataTable $Process -PreContent { New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center} -Buttons @() -DisableSearch -DisablePaging -HideFooter
            }
            Panel {
                Table -DataTable $Process -PreContent { New-HTMLText -Text 'TestPostContent' -Color DodgerBlue -Alignment center} -Buttons @() -DisableSearch -DisablePaging -HideFooter
            }
        }
    }

}
```

I don't see what you mean for left justfication

**Comment by g-pearl** [comment]
if you change the panel table to include "-buttons @() -DisableSearch -HideFooter -DisablePaging"  The table is 4-5 columns that only take up a small portion of the screen and is centered in the active window instead of on the left side.

**Comment by PrzemyslawKlys** [comment]
Ok, I see. Don't use Collapsed. When it's collapsed DataTable is broken.

**Comment by g-pearl** [comment]
is it possible to add pictures and that might help.

**Comment by PrzemyslawKlys** [comment]
https://github.com/EvotecIT/Dashimo/issues/5 - It's an issue I need to work on later.

**Comment by PrzemyslawKlys** [comment]
As for pictures. Later. Feel free to open new issue ;)

**Comment by g-pearl** [comment]
Pictures not in DASHIMO but to help explain what I was taking about.  Within GITHUB.  This is great thanks I will watch issue #5 --  Thanks again for all your help.

I will close this out.  Thanks
