### ISSUE TITLE
Export to PDF Format Issue

### ISSUE THREAD

**Issue by ferwe** [EvotecIT/Dashimo#9]
After exporting to PDF the content is cut.

Maybe it could be a solution to use the landscape format.
Also it would be good if the content could be scaled automatically.
And at least A3 may be the better size.

Are you using datatables?
https://datatables.net/

![image](https://user-images.githubusercontent.com/36640422/58151328-9aadc300-7c69-11e9-9c9a-83c82249340e.png)

**Comment by PrzemyslawKlys** [comment]
Yes, I'm using datatables.net and I have no control in PS over this. If datatables allows control of PDF I need to verify this functionality.

**Comment by PrzemyslawKlys** [comment]
It does seem to have that options:

https://datatables.net/extensions/buttons/examples/html5/pdfPage.html

I'll explore what can be done

**Comment by ferwe** [comment]
I found a similar module for creating html tables.
Not with this amount of features like Dashimo, but for my needs it was ok.

I can't solve the issue completely, but I put some colde like this inside the script.
Maybe it helps.

{
extend: 'pdfHtml5',
text: 'Save as PDF',
filename: 'ReportExport',
title: 'Exported Data',
orientation: 'landscape',
pageSize: 'A3',
exportOptions: {
rows: ':visible',
columns: ':visible',
modifier: {
page: 'current'
  }
},

**Comment by PrzemyslawKlys** [comment]
Yes, it helps. I'll verify this functionality and add it in.

**Comment by PrzemyslawKlys** [comment]
I've added this but I am not sure whether I should allow for customization of all those options and if so in what way. I guess I could probably allow config the same way you do TableConditionalFormatting so each setting for each button can be configured.

**Comment by PrzemyslawKlys** [comment]
This new commit added this:

```powershell
$Process = Get-Process | Select-Object -First 15 | Select name, Priorityclass, fileversion, handles, cpu

Dashboard -Name 'Dashimo Test' -FilePath $PSScriptRoot\DashboardEasy05.html -Show {
    Section -Name 'Test' -Collapsable {
        Container {
            Panel {
                Table -DataTable $Process {
                    TableButtonPDF
                    TableButtonCopy
                    TableButtonExcel
                 } -Buttons @() -DisableSearch -DisablePaging -HideFooter
            }
            Panel {
                Table -DataTable $Process -Buttons @() -DisableSearch -DisablePaging -HideFooter
            }
            Panel {
                Table -DataTable $Process {
                    TableButtonPDF -PageSize A10 -Orientation landscape
                    TableButtonCopy
                    TableButtonExcel
                 } -Buttons @() -DisableSearch -DisablePaging -HideFooter
            }
        }
    }

}
```

This means that one can define buttons in different way. When "custom" way is used `Buttons` will be ignored regardless if it's set or not.

**Comment by PrzemyslawKlys** [comment]
Added options. Will be released later.
